service: algovis

frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.8
  region: us-east-1
  memorySize: 256
  timeout: 30
  environment:
    STAGE: ${opt:stage, 'dev'}
    PYTHON_PATH: /var/runtime:/var/task

package:
  patterns:
    - "!node_modules/**"
    - "!frontend/**"
    - "!.git/**"
    - "!.env"
    - "backend/**"
    - "algorithms/**"
    - "requirements.txt"
    - "!**/__pycache__/**"
    - "!**/*.pyc"
    - "!**/*.pyo"
    - "!**/*.pyd"

functions:
  api:
    handler: backend/lambda_handler.handler
    events:
      - httpApi:
          path: /health
          method: GET
      - httpApi:
          path: /api/algorithms
          method: GET
      - httpApi:
          path: /api/graph/sample
          method: GET
      - httpApi:
          path: /api/graph/traverse/{algorithm}
          method: POST
      - httpApi:
          path: /api/dp/knapsack
          method: POST
      - httpApi:
          path: /api/dp/lcs
          method: POST
      - httpApi:
          path: /api/dp/matrix-chain
          method: POST
      - httpApi:
          path: /api/optimization/simplex
          method: POST
      - httpApi:
          path: /api/optimization/max-flow
          method: POST
      - httpApi:
          path: /api/optimization/min-cost-flow
          method: POST
      - httpApi:
          path: /api/optimization/gradient-descent
          method: POST
      - httpApi:
          path: /api/optimization/constrained
          method: POST
      - httpApi:
          path: /api/benchmark/{algorithm}
          method: POST
    layers:
      - !Ref PythonDependenciesLambdaLayer

layers:
  pythonDependencies:
    name: python-deps
    description: Python dependencies for AlgoVis
    compatibleRuntimes:
      - python3.8
    package:
      patterns:
        - "!**"
        - "python/**"

resources:
  Resources:
    PythonDependenciesLambdaLayer:
      Type: AWS::Lambda::LayerVersion
      Properties:
        LayerName: python-deps
        Description: Python dependencies for AlgoVis
        Content:
          S3Bucket: ${self:custom.deploymentBucket}
          S3Key: layers/python-deps.zip
        CompatibleRuntimes:
          - python3.8

custom:
  deploymentBucket: algovis-deployment-${opt:stage, 'dev'}
  pythonRequirements:
    layer:
      name: python-deps
      description: Python dependencies for AlgoVis
    noDeploy:
      - pytest
      - black
      - mypy
      - pylint
